---
- hosts: webservers
  gather_facts: yes
  tasks:
   - name: Update apt cache
     become: yes
     apt:
      update_cache: yes
   - name: nginx installation
     become: yes
     apt:
      name: nginx
      state: latest
   - name: Install php-fpm ver7.4
     become: yes
     apt:
      name: php7.4-fpm
      state: present
   - name: start nginx
     become: yes
     service:
         name: nginx
         state: started
   - name: Copy the php file
     become: yes
     copy:
       src: index.php
       dest: /var/www/html/
   - name: Add the template file
     become: yes
     template:
       src: temps/nginx.conf
       dest: /etc/nginx/sites-available/default
   - name: Enable the configuration file
     become: yes
     file:
       src: /etc/nginx/sites-available/default
       dest: /etc/nginx/sites-enabled/default
       state: link
   - name: Restart
     become: yes
     service:
          name: nginx
          state: restarted

- hosts: haproxy
  gather_facts: yes
  become: yes
  tasks:
   - name: Update cache 
     apt:
      update_cache: yes
   - name: Install haproxy
     become: yes
     apt:
      name: haproxy
      state: present
   - name: Update HAProxy file
     template:
      src: temps/haproxy.cfg.j2
      dest: /etc/haproxy/haproxy.cfg
   - name: Restart HAProxy
     service:
       name: haproxy
       state: restarted
